[project]
name = "aws-realtime-voice-assistant-example"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "aiofile>=3.9.0",
    "boto3>=1.37.37",
    "langchain>=0.3.23",
    "langchain-aws>=0.2.21",
]
